services:
  ml:
    build:
      context: ../../
      dockerfile: tasks/ml/Dockerfile
    ports:
      - "9051:9051"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - TASK_MODE=inference
